#include "includes.h"

ROM_DATA const u16 *level_defines[][4] = {
   { stereomadness_l1_level_data, stereomadness_l2_level_data, stereomadness_spr_data, (u16 *) stereomadness_properties },
   { backontrack_l1_level_data, backontrack_l2_level_data, backontrack_spr_data, (u16 *) backontrack_properties },
   { polargeist_l1_level_data, polargeist_l2_level_data, polargeist_spr_data, (u16 *) polargeist_properties },
   { dryout_l1_level_data, dryout_l2_level_data, dryout_spr_data, (u16 *) dryout_properties },
   { baseafterbase_l1_level_data, baseafterbase_l2_level_data, baseafterbase_spr_data, (u16 *) baseafterbase_properties },
   { cantletgo_l1_level_data, cantletgo_l2_level_data, cantletgo_spr_data, (u16 *) cantletgo_properties },
   { jumper_l1_level_data, jumper_l2_level_data, jumper_spr_data, (u16 *) jumper_properties },
   { timemachine_l1_level_data, timemachine_l2_level_data, timemachine_spr_data, (u16 *) timemachine_properties },
   { cycles_l1_level_data, cycles_l2_level_data, cycles_spr_data, (u16 *) cycles_properties },
   { xstep_l1_level_data, xstep_l2_level_data, xstep_spr_data, (u16 *) xstep_properties },
   { clutterfunk_l1_level_data, clutterfunk_l2_level_data, clutterfunk_spr_data, (u16 *) clutterfunk_properties },
   { theoryofeverything_l1_level_data, theoryofeverything_l2_level_data, theoryofeverything_spr_data, (u16 *) theoryofeverything_properties },
   { electromanadventures_l1_level_data, electromanadventures_l2_level_data, electromanadventures_spr_data, (u16 *) electromanadventures_properties },
   { clubstep_l1_level_data, clubstep_l2_level_data, clubstep_spr_data, (u16 *) clubstep_properties },
   { electrodynamix_l1_level_data, electrodynamix_l2_level_data, electrodynamix_spr_data, (u16 *) electrodynamix_properties },
   { hexagonforce_l1_level_data, hexagonforce_l2_level_data, hexagonforce_spr_data, (u16 *) hexagonforce_properties },
   { blastprocessing_l1_level_data, blastprocessing_l2_level_data, blastprocessing_spr_data, (u16 *) blastprocessing_properties },
   { theoryofeverything2_l1_level_data, theoryofeverything2_l2_level_data, theoryofeverything2_spr_data, (u16 *) theoryofeverything2_properties },
   { autocycles_l1_level_data, autocycles_l2_level_data, autocycles_spr_data, (u16 *) autocycles_properties },
   { sonar_l1_level_data, sonar_l2_level_data, sonar_spr_data, (u16 *) sonar_properties },
   { retray_l1_level_data, retray_l2_level_data, retray_spr_data, (u16 *) retray_properties },
   { invisontrack_l1_level_data, invisontrack_l2_level_data, invisontrack_spr_data, (u16 *) invisontrack_properties },
   { leveleasy_l1_level_data, leveleasy_l2_level_data, leveleasy_spr_data, (u16 *) leveleasy_properties },
   { dorabaebasic_l1_level_data, dorabaebasic_l2_level_data, dorabaebasic_spr_data, (u16 *) dorabaebasic_properties },
   { dorabaebasic4_l1_level_data, dorabaebasic4_l2_level_data, dorabaebasic4_spr_data, (u16 *) dorabaebasic4_properties },
   { dorabaebasic7_l1_level_data, dorabaebasic7_l2_level_data, dorabaebasic7_spr_data, (u16 *) dorabaebasic7_properties },
   { goldenclub_l1_level_data, goldenclub_l2_level_data, goldenclub_spr_data, (u16 *) goldenclub_properties },
   { squareadv_l1_level_data, squareadv_l2_level_data, squareadv_spr_data, (u16 *) squareadv_properties },
   { selectpaymenttype_l1_level_data, selectpaymenttype_l2_level_data, selectpaymenttype_spr_data, (u16 *) selectpaymenttype_properties },
   { storymadness_l1_level_data, storymadness_l2_level_data, storymadness_spr_data, (u16 *) storymadness_properties },
   { groundtospace_l1_level_data, groundtospace_l2_level_data, groundtospace_spr_data, (u16 *) groundtospace_properties },
   { one_l1_level_data, one_l2_level_data, one_spr_data, (u16 *) one_properties },
   { dynamicontrack_l1_level_data, dynamicontrack_l2_level_data, dynamicontrack_spr_data, (u16 *) dynamicontrack_properties },
   { iceland_l1_level_data, iceland_l2_level_data, iceland_spr_data, (u16 *) iceland_properties },
   { ultimatedestruction_l1_level_data, ultimatedestruction_l2_level_data, ultimatedestruction_spr_data, (u16 *) ultimatedestruction_properties },
   { pyrophoric_l1_level_data, pyrophoric_l2_level_data, pyrophoric_spr_data, (u16 *) pyrophoric_properties },
   { cantletgov2_l1_level_data, cantletgov2_l2_level_data, cantletgov2_spr_data, (u16 *) cantletgov2_properties },
   { funnygameholiday_l1_level_data, funnygameholiday_l2_level_data, funnygameholiday_spr_data, (u16 *) funnygameholiday_properties },
   { revolution_l1_level_data, revolution_l2_level_data, revolution_spr_data, (u16 *) revolution_properties },
   { tig_oglevel_l1_level_data, tig_oglevel_l2_level_data, tig_oglevel_spr_data, (u16 *) tig_oglevel_properties },
   { fireaura_tig_l1_level_data, fireaura_tig_l2_level_data, fireaura_tig_spr_data, (u16 *) fireaura_tig_properties },
   { thenightmare_l1_level_data, thenightmare_l2_level_data, thenightmare_spr_data, (u16 *) thenightmare_properties },
   { demonjumper_l1_level_data, demonjumper_l2_level_data, demonjumper_spr_data, (u16 *) demonjumper_properties },
   { rose_l1_level_data, rose_l2_level_data, rose_spr_data, (u16 *) rose_properties },
   { problematic_l1_level_data, problematic_l2_level_data, problematic_spr_data, (u16 *) problematic_properties },
   { deathmoon_l1_level_data, deathmoon_l2_level_data, deathmoon_spr_data, (u16 *) deathmoon_properties },
   { acropolis_l1_level_data, acropolis_l2_level_data, acropolis_spr_data, (u16 *) acropolis_properties },
   { kaleidoscopic_l1_level_data, kaleidoscopic_l2_level_data, kaleidoscopic_spr_data, (u16 *) kaleidoscopic_properties },
   { everyend_l1_level_data, everyend_l2_level_data, everyend_spr_data, (u16 *) everyend_properties },
   { test_l1_level_data, test_l2_level_data, test_spr_data, (u16 *) test_properties },
   { test2_l1_level_data, test2_l2_level_data, test2_spr_data, (u16 *) test2_properties },
   { endless_l1_level_data, endless_l2_level_data, endless_spr_data, (u16 *) endless_properties },
};

ROM_DATA const u8 *level_names[] = {
   stereomadness_name,
   backontrack_name,
   polargeist_name,
   dryout_name,
   baseafterbase_name,
   cantletgo_name,
   jumper_name,
   timemachine_name,
   cycles_name,
   xstep_name,
   clutterfunk_name,
   theoryofeverything_name,
   electromanadventures_name,
   clubstep_name,
   electrodynamix_name,
   hexagonforce_name,
   blastprocessing_name,
   theoryofeverything2_name,
   autocycles_name,
   sonar_name,
   retray_name,
   invisontrack_name,
   leveleasy_name,
   dorabaebasic_name,
   dorabaebasic4_name,
   dorabaebasic7_name,
   goldenclub_name,
   squareadv_name,
   selectpaymenttype_name,
   storymadness_name,
   groundtospace_name,
   one_name,
   dynamicontrack_name,
   iceland_name,
   ultimatedestruction_name,
   pyrophoric_name,
   cantletgov2_name,
   funnygameholiday_name,
   revolution_name,
   tig_oglevel_name,
   fireaura_tig_name,
   thenightmare_name,
   demonjumper_name,
   rose_name,
   problematic_name,
   deathmoon_name,
   acropolis_name,
   kaleidoscopic_name,
   everyend_name,
   test_name,
   test2_name,
   endless_name,
};
